version: '3.9'
services:
  web-check:
    container_name: Web-Check
    image: lissy93/web-check
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 7070:3000 




